### ISSUE TITLE
Generate screen

### ISSUE THREAD

**Issue by RWOverdijk** [infinitered/ignite-ir-next#18]
```
$ ignite generate screen Activity

✔︎ App/Containers/ActivityScreen.js
✔︎ App/Containers/Styles/ActivityScreenStyle.js
vvv -----[ DEBUG ]----- vvv
Error: 'import { StackNavigator } from' was not found in file ./App/Navigation/AppNavigation.js.
    at Object.insertInFile (/Users/rwoverdijk/.nvm/versions/node/v7.8.0/lib/node_modules/ignite-cli/src/extensions/patching.js:31:33)
    at Object.patchInFile (/Users/rwoverdijk/.nvm/versions/node/v7.8.0/lib/node_modules/ignite-cli/src/extensions/ignite/patchInFile.js:44:16)
    at Object.module.exports [as run] (./node_modules/ignite-ir-next/commands/screen.js:48:12)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
^^^ -----[ DEBUG ]----- ^^^
```

Which makes sense. I implemented Redux in my app (sort of, still trying) so the import line looks like this:

```js
import {StackNavigator, addNavigationHelpers} from 'react-navigation';
```

If this is regex, maybe just look for `from 'react-navigation';` instead. It doesn't matter what gets imported.

**Comment by GantMan** [comment]
Good catch!  Will check on this.
